### ISSUE TITLE
‘problem file' can't found

### ISSUE THREAD

**Issue by tjuxiaofeng** [TAMU-VITA/LISTA-CPSS#1]
Thanks for your sharing. I meet some trouble while running your codes. It seams that the problem file isn't include in your project which should contain a '.npz' or '.mat' file. How can I get them?

**Comment by songyh15** [comment]
You can use the file 'prob.py' in the 'utils' folder to generate the '.npz' file.

**Comment by songyh15** [comment]
> Thanks for your sharing. I meet some trouble while running your codes. It seams that the problem file isn't include in your project which should contain a '.npz' or '.mat' file. How can I get them?

You can use the file 'prob.py' in the 'utils' folder to generate the '.npz' file.

**Comment by songyh15** [comment]
Thanks for your sharing.  Can I get the dictionary file of the BSD500 set?

**Comment by xhchrn** [comment]
> 
> 
> Thanks for your sharing. Can I get the dictionary file of the BSD500 set?

Sure. Here is a dictionary file in the npy file form. If you have trouble accessing it, please let me know.

https://www.dropbox.com/s/v0rx27wbcgvee1h/D.npy?dl=0
